backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Nyheter"
    folder: "src/pages/nyheter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime", date_format: "DD.MM.YYYY"}
      - {label: "Meta beskrivning", name: "description", widget: "text"}
      # - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Bild", name: "featuredimage", widget: image}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Taggar", name: "tags", widget: "list"}

  - name: "tjanster"
    label: "Tjänster"
    folder: "src/pages/tjanster"
    create: true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single-service-page"}
      - {label: "Titel", name: "title", widget: "string"}
      # - {label: "Publicerat datum", name: "date", widget: "datetime"}
      # - {label: "Beskrivning", name: "description", widget: "text"}
      # - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Beskrivning", name: "description", widget: "text", hint: "En kortare beskrivning som visas på tjänster sidan."}
      # - {label: "Visa på startsida", name: "displayOnStartPage", widget: "boolean", required: false}
      - {label: "Bild", name: "featuredimage", widget: image}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Taggar", name: "tags", widget: "list"}


  - name: "taplan"
    label: "Ta-planer & Tillstånd"
    folder: "src/pages/taplaner-och-tjanster"
    create: true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single-taplan-page"}
      - {label: "Titel", name: "title", widget: "string"}
      # - {label: "Publicerat datum", name: "date", widget: "datetime"}
      # - {label: "Beskrivning", name: "description", widget: "text"}
      # - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Beskrivning", name: "description", widget: "text", hint: "En kortare beskrivning som visas på tjänster sidan."}
      # - {label: "Visa på startsida", name: "displayOnStartPage", widget: "boolean", required: false}
      - {label: "Bild", name: "featuredimage", widget: image}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Taggar", name: "tags", widget: "list"}


  - name: "produkter"
    label: "Produkter"
    folder: "src/pages/produkter"
    create: true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single-product-page"}
      - {label: "Titel", name: "title", widget: "string"}
      # - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "markdown"}
      # - {label: "Visa på startsida", name: "displayOnStartPage", widget: "boolean", required: false}

      - {label: "Bild", name: "featuredimage", widget: image}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Taggar", name: "tags", widget: "list"}
      - {label: "Filer", name: "files", required: false, widget: list, fields: [{label: "fil", name: "file", widget: file}, {label: "filnamn", name: "filename", widget: "string"}]}

  - name: "pages"
    label: "Sidor"
    files:
      - file: "src/pages/index.md"
        label: "Startsidan"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Titel, name: title, widget: string}
          - {label: Jumbotron bild, name: image, widget: image}
          - {label: Rubrik, name: heading, widget: string}
          # - {label: Underrubrik, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: "Bild", name: "image", widget: "image"}, {label: titel, name: title, widget: string}, {label: innehåll, name: text, widget: markdown}]}
          - {label: Description, name: description, widget: string}
          - {label: "Intro", name: "intro", widget: "object", fields: [{label: info-box, name: blurbs, widget: "list", fields: [{label: "Rubrik", name: "heading", widget: "string"}, {label: "Bild", name: "image", widget: "image"}, {label: "Text", name: "text", widget: "markdown"}, {label: "ikon", name: "icon", widget: "select", options: ["directions", "road", "map" ]}, {label: "knapplänk", name: "buttonLink", widget: "string" } ]}]}
      - file: "src/pages/om-foretaget/index.md"
        label: "Om företaget"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Titel", name: "title", widget: "string"}
          - {label: Image, name: image, widget: image}
          - {label: "Innehåll", name: "body", widget: "markdown"}
      # - file: "src/pages/tjanster/index.md"
      #   label: "Tjänster"
      #   name: "service"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service-page"}
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Products, name: products, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}, {label: Rubrik, name: heading, widget: string}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      # - file: "src/pages/produkter/index.md"
      #   label: "Produkter"
      #   name: "products"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Products, name: products, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}, {label: Rubrik, name: heading, widget: string}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/data/contact.yml"
        label: "Kontakta oss"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact"}
          - {label: E-post Tillstånd, name: mailTillstand, widget: string}
          - {label: E-post Material och tjänster, name: mailMaterial, widget: string}
          - {label: E-post Ekonomi, name: mailEkonomi, widget: string}

          - {label: Telefon Tillstånd, name: phoneTillstand, widget: string}
          - {label: Telefon Material och tjänster, name: phoneMaterial, widget: string}
          - {label: Telefon Ekonomi, name: phoneEkonomi, widget: string}

          - {label: Besöksadress Tillstånd, name: visitAddressTillstand, widget: text}
          - {label: Besöksadress Material och tjänster, name: visitAddressMaterial, widget: text}

          - {label: karta, name: mapImage, widget: image}
          - {label: "page", name: "page", widget: "hidden", default: "contact"}

  - name:  "staff"
    label: "Anställda"
    files:
      - file: "src/data/administration.yml"
        label: "Administration"
        name: "administration"
        fields:
          - {name: templateKey, label: Template Key, widget: hidden, default: staff}
          - label: Administration
            name: "administration"
            widget: list
            fields:
              - {label: Namn, name: name, widget: string}
              - {label: Roll, name: position, widget: string}
              - {label: telefon, name: phone, widget: number}
              - {label: email, name: email, widget: string}
              - {label: bild, name: photo, widget: image}

      - file: "src/data/tillstand.yml"
        label: "Tillstånd"
        name: "tillstand"
        fields:
          - {name: templateKey, label: Template Key, widget: hidden, default: staff}
          - label: Tillstånd
            name: "tillstand"
            widget: list
            fields:
              - {label: Namn, name: name, widget: string}
              - {label: Roll, name: position, widget: string}
              - {label: telefon, name: phone, widget: number}
              - {label: email, name: email, widget: string}
              - {label: bild, name: photo, widget: image}


      - file: "src/data/utstallning-transport.yml"
        label: "Utställning/transport"
        name: "utstallning-transport"
        fields:
          - {name: templateKey, label: Template Key, widget: hidden, default: staff}
          - label: Utställning/transport
            name: "utstallning-transport"
            widget: list
            fields:
              - {label: Namn, name: name, widget: string}
              - {label: Roll, name: position, widget: string}
              - {label: telefon, name: phone, widget: number}
              - {label: email, name: email, widget: string}
              - {label: bild, name: photo, widget: image}


